%environmentParameters=struct(...
%   n_healthy_goals,V_n_healthy_goals,...
%   rew_Goals,Vrew_Goals,...
%   p_GetRewardGoals,Vp_GetRewardGoals
%   n_drug_goals,V_n_drug_goals,...
%   rew_DG,V_rew_DG,...
%   pun_DG,V_pun_DG,...
%   escaLation_factor_DG,V_escaLation_factor_DG,...
%   n_base_states,V_n_base_states,...
%   deterministic,V_deterministic);

function  Environment=TestCreateEnvironment()
environmentParameters=struct(...
  'n_healthy_goals',1,...  
  'rew_Goals',[1],...
  'p_GetRewardGoals',0.5,...
  'n_drug_goals',1,...
  'rew_DG',1,...
  'rew_DGV',[1,0.5],...
  'pun_DG',-0.5,...
  'pun_DGV',[-0.5,-0.75],...
  'pDG',[0.5],...
  'pDGV',[0.5,0.25],...
  'escaLation_factor_DG',0.5,...
  'n_base_states',5,...
  'deterministic',false,...
  'autoGen',1);

 Environment=CreateEnvironmentMultiStepSequential(environmentParameters);
 
 displayEnvironment(Environment);
 
 
end